builders:
  widgetBuilder:
    import: "package:objd_gen/builders.dart"
    builder_factories: ["widgetBuilder"]
    build_extensions: { ".dart": [".widget.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
