name: objd_gen
description: A package of code generators for objD Annotations
version: 0.0.4
homepage: https://objd.stevertus.com
documentation: https://objd.stevertus.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build: ^2.4.0
  build_config: ^1.1.1
  analyzer: ^5.2.0
  source_gen: ^1.3.2
  objd: ^0.4.5
dev_dependencies:
  lints: ^1.0.1
