name: objd_gen
description: A package of code generators for objD Annotations
version: 0.0.2
homepage: https://objd.stevertus.com
documentation: https://objd.stevertus.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.0.0
  build_config: ^0.4.7
  analyzer: ^1.3.0
  source_gen: ^1.0.0
  objd:
dev_dependencies:
  pedantic: ^1.11.0
