name: objd_gen
description: A package of code generators for objD Annotations
version: 0.0.1
homepage: https://objd.stevertus.com
documentation: https://objd.stevertus.com
author: Stevertus <contact@stevertus.com>

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  build: ^1.3.0
  build_config: ^0.4.0
  source_gen: ^0.9.0
  objd:
    path: ../objectiveD
dev_dependencies:
  pedantic: ^1.9.2
